---
- name: Play to start the services of WLS domain
  hosts: oci_dev
  become: true
  become_user: "{{ WLS_USER }}"
  vars_files:
    - '{{ playbook_dir }}/wls_variables.yml'
  tasks:
    - name: Lifecycle stop
      tags: stop
      block:
        - name: Stop Admin Server
          tags: stopAdmin
          shell:
            "{{ DOMAIN_HOME }}/{{ DOMAIN_NAME }}/bin/stopWebLogic.sh"
            
        - name: Stop NodeManager
          tags: stopNodeManager
          shell:
            "{{ DOMAIN_HOME }}/{{ DOMAIN_NAME }}/bin/stopNodeManager.sh"
    - name: Lifecycle start
      tags: start
      block:
        - name: Start the Node Manager
          tags: startNodeManager
          shell:  
            "nohup {{DOMAIN_HOME}}/{{DOMAIN_NAME}}/bin/startNodeManager.sh > {{DOMAIN_HOME}}/{{DOMAIN_NAME}}/bin/startNodeManager.log 2>&1 &"
            
        - name: Start the Weblogic Adminstrator
          tags: startAdmin
          shell: 
            "nohup {{DOMAIN_HOME}}/{{DOMAIN_NAME}}/bin/startWebLogic.sh > {{DOMAIN_HOME}}/{{DOMAIN_NAME}}/servers/dojo-wls-admin-server/logs/dojo-wls-admin-server.out 2>&1 &"
... 
