---
- name: Domain update using WDT
  hosts: dojoserver
  vars_files:
    - '{{ playbook_dir }}/wls_variables.yml'
  any_errors_fatal: true
  gather_facts: true
  become: yes
  become_user: "{{ WLS_USER }}"

  # NB! ensure that you installed the WDT collection!
  # ansible-galaxy collection install zeusbaba.wdt
  collections:
    - zeusbaba.wdt
  roles:
    - wdt_updatedomain

  pre_tasks:
    - name: Ensure that relevant paths are set for bash env
      blockinfile:
        path: "{{ item }}"
        marker: "# {mark} ANSIBLE_MANAGED envs_home"
        insertafter: EOF # ".*export TBD_HOME.*\n"
        block: |
          export JAVA_HOME={{ JAVA_HOME }}
          export PATH=$JAVA_HOME/bin:$PATH
          ORACLE_HOME={{ ORACLE_HOME }}
          export WDT_HOME={{ WDT_HOME }}
      loop:
        - "$HOME/.bashrc"

  tasks:
    - name: "Update domain using 'wdt_updatedomain role'"
      import_role:
        name: wdt_updatedomain
      vars:
        # templates to use for this role, NB! must be well structured according to WDT template format
        wdt_templates: ["WDT_template-ldapProviders.yaml"]
        # to create more complex domain type definitions, see https://oracle.github.io/weblogic-deploy-tooling/userguide/tools-config/domain_def/
        wdt_domain_type: "WLS"
        wdt_user: "{{ WLS_USER }}"
        wdt_group: "{{ WLS_GROUP }}"
        wdt_templates_home: "{{ WDT_TEMPLATES_HOME }}"
        java_home: "{{ JAVA_HOME }}"
        mw_home: "{{ ORACLE_HOME }}"
        domain_root: "{{ DOMAIN_HOME }}/{{ DOMAIN_NAME }}"
        domain_home: "{{ DOMAIN_HOME }}/{{ DOMAIN_NAME }}"
      tags:
        - wdt-offline
        - update-domain