---
- name: Install and Configure Fusion Middleware (FMW)
  hosts: dojoserver
  vars_files:
    - '{{ playbook_dir }}/variables.yml'
  roles:
    - dojo-jdk-installer
    - dojo-fmw-installer
#    - WLS_Domain_Create
