---
- name: Install and Configure Fusion Middleware (FMW)
  hosts: dojoserver
  gather_facts: true
  vars_files:
    - '{{ playbook_dir }}/wls_variables.yml'
  roles:
   #  - dojo-jdk-installer
  #   - dojo-wls-installer
     - dojo-wdt-createdomain
