---
- name: Install and Configure Fusion Middleware (FMW)
  hosts: dojoserver
  become: yes
  become_user: "{{ WLS_USER }}"
  
  vars_files:
    - '{{ playbook_dir }}/wls_variables.yml'
  roles:
    - dojo-jdk-installer
    - dojo-wls-installer
#    - WLS_Domain_Create
