---
- name: Domain Discover using WDT
  hosts: dojoserver
  become: yes
  become_user: "{{ WLS_USER }}"
  vars_files:
    - '{{ playbook_dir }}/wls_variables.yml'
  vars:
    run_wdt_action: "discover-domain-offline"
  any_errors_fatal: true
  gather_facts: true
  
  collections:
    - zeusbaba.wdt
  roles:
    - wdt_discoverdomain


  pre_tasks:
    - name: ensure that relevant paths are set for bash env
      blockinfile:
        path: "{{ item }}"
        marker: "# {mark} ANSIBLE_MANAGED envs_home"
        insertafter: EOF # ".*export TBD_HOME.*\n"
        block: |
          export JAVA_HOME={{ JAVA_HOME }}
          export PATH=$JAVA_HOME/bin:$PATH
          ORACLE_HOME={{ ORACLE_HOME }}
          export WDT_HOME={{ WDT_HOME }}
      loop:
        - "$HOME/.bashrc"

  tasks:
    - name: Discover existing domain using 'WDT_discoverDomain role'
      import_role:
        name: wdt_discoverdomain        
      vars:
        wdt_user: "WLS_USER"
        wdt_group: "WLS_GROUP"
        workdir: "/home/{{ WLS_USER }}"
        java_home: "{{ JAVA_HOME }}"
        mw_home: "{{ ORACLE_HOME }}"
        domain_home: "{{ DOMAIN_HOME }}/{{ DOMAIN_NAME }}"
        wdt_home: "{{ WDT_HOME }}"
        wdt_templates_home: "{{ workdir }}/wdt-templates"
        wdt_archive_file: "WDT_template-discovered_offline.zip"
        wdt_template_file: "WDT_template-discovered_offline.yaml"
        wdt_domain_type: "WLS"
      tags:
        - wdt-offline
        - discover-domain