---
- name: Domain creation using WDT
  hosts: oci_dev
  vars_files:
    - '{{ playbook_dir }}/wls_variables.yml'
  any_errors_fatal: true
  gather_facts: true
  become: yes
  become_user: "{{ WLS_USER }}"

  # NB! ensure that you installed the WDT collection!
  # ansible-galaxy collection install zeusbaba.wdt
  collections:
    - zeusbaba.wdt
  roles:
    - wdt_setup
    - wdt_createdomain
    #TODO: - wdt_updatedomain

  pre_tasks:
    - name: ensure that relevant paths are set for bash env
      blockinfile:
        path: "{{ item }}"
        marker: "# {mark} ANSIBLE_MANAGED envs_home"
        insertafter: EOF # ".*export TBD_HOME.*\n"
        block: |
          export JAVA_HOME={{ JAVA_HOME }}
          export PATH=$JAVA_HOME/bin:$PATH
          ORACLE_HOME={{ ORACLE_HOME }}
          export WDT_HOME={{ WDT_HOME }}
      loop:
        - "$HOME/.bashrc"

  tasks:

    - name: "setup WDT binaries using 'WDT_setup role'"
      import_role:
        name: wdt_setup
      vars:
        # NB! change if you want to override which WDT version will be installed
        # See https://github.com/oracle/weblogic-deploy-tooling/releases
        wdt_distribution_version: "2.2.0"
        wdt_user: "{{ WLS_USER }}"
        wdt_group: "{{ WLS_GROUP }}"
        wdt_home: "{{ WDT_HOME }}"
        wdt_templates_home: "{{ WDT_TEMPLATES_HOME }}"
      tags:
        - wdt-offline
        - setup

    - name: "Create new domain using 'WDT_createDomain role'"
      import_role:
        name: wdt_createdomain
      vars:
        # templates to use for this role, NB! must be well structured according to WDT template format
        wdt_templates: ["WDT_template-baseline.yaml"]
        # to create more complex domain type definitions, see https://oracle.github.io/weblogic-deploy-tooling/userguide/tools-config/domain_def/
        wdt_domain_type: "WLS"
        wdt_user: "{{ WLS_USER }}"
        wdt_group: "{{ WLS_GROUP }}"
        wdt_templates_home: "{{ WDT_TEMPLATES_HOME }}"
        #workdir: "/home/{{ WLS_USER }}"
        java_home: "{{ JAVA_HOME }}"
        mw_home: "{{ ORACLE_HOME }}"
        domain_root: "{{ DOMAIN_HOME }}"

      tags:
        - wdt-offline
        - create-domain
