---
- name: Install and Configure Fusion Middleware (FMW)
  hosts: oci_dev
  vars_files:
    - '{{ playbook_dir }}/wls_variables.yml'
  roles:
#    - dojo-jdk-installer
    - dojo-wls-installer
#    - WLS_Domain_Create
