---
- name: Install and Configure Fusion Middleware (FMW)
  hosts: oci_dev
  vars_files:
    - '{{ playbook_dir }}/variables.yml'
  roles:
    - dojo-jdk-installer
    - dojo-fmw-installer
#    - dojo-wls-installer
